#!/bin/bash

# Ayn Wine - Public Access Setup Script
# This script exposes your local development servers publicly

echo "🍷 Ayn Wine - Public Access Setup"
echo "=================================="
echo ""
echo "Your development servers are running locally at:"
echo "  Frontend (Next.js): http://localhost:3000"
echo "  Backend (API):      http://localhost:3001"
echo ""
echo "To make them publicly accessible, you have several options:"
echo ""
echo "1️⃣  VS CODE PORT FORWARDING (Recommended for GitHub Codespaces)"
echo "   - Click on the PORTS tab at the bottom of VS Code"
echo "   - Right-click on port 3000 and select 'Make Public'"
echo "   - Right-click on port 3001 and select 'Make Public'"
echo "   - Click the globe icon to open the public link"
echo ""
echo "2️⃣  NGROK TUNNEL (Free alternative)"
echo "   - Sign up at https://ngrok.com"
echo "   - Get your authtoken from https://dashboard.ngrok.com/get-started/your-authtoken"
echo "   - Run: ngrok config add-authtoken YOUR_TOKEN_HERE"
echo "   - Then run this script with: bash scripts/expose.sh"
echo ""
echo "3️⃣  GITHUB CODESPACES PORT FORWARDING"
echo "   - Ports are automatically forwarded in GitHub Codespaces"
echo "   - Check the PORTS tab to make them public"
echo ""
echo "=================================="
echo ""
echo "Current local URLs:"
echo "  Frontend: http://localhost:3000"
echo "  Backend:  http://localhost:3001"
echo "  API Docs: http://localhost:3001/api-docs"
